services:
  webapp:
    build: ./go
    environment:
      ISUCON_DB_HOST: 192.168.0.12
      ISUCON_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
      NEW_RELIC_LICENSE_KEY: eabdcd2b59a57d280ac659365a8dcf9eFFFFNRAL
    network_mode: host
    volumes:
      - /home/isucon/webapp/tenant_db:/home/isucon/webapp/tenant_db
      - /home/isucon/webapp/sql:/home/isucon/webapp/sql
      - /home/isucon/webapp/public.pem:/home/isucon/webapp/public.pem:ro
      - /home/isucon/initial_data:/home/isucon/initial_data
      - /home/isucon/tmp:/home/isucon/tmp
    init: true
